// <auto-generated />
namespace Tech2019.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migPCactiondetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migPCactiondetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202502251425394_mig-PC-action-detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
